[package]
name = "phd_cand"
version = "0.1.0"
edition = "2021"

[lib]
name = "phd_cand"
crate-type = ["lib"]

[dependencies]
lru = "0.12.4"
rand = "0.8.5"
random_choice = "0.3.2"
regex = "1.10.6"
eval = "0.4.3"