[package]
name = "phd-cand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
levenshtein = "1.0.5"
lru = "0.12.4"
rand = "0.8.5"
random_choice = "0.3.2"
